<a href="https://colab.research.google.com/github/maeng-gun/python_basic/blob/main/pandas_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 탐색하기

### 1. 데이터프레임 탐색하기

In [ ]:
import pandas as pd

df = pd.read_excel('https://maeng-gun.github.io/pandas/raw_data_1.xlsx',thousands=',')

#### 1) 기본 속성

* 인덱스명(index)

In [ ]:
df.index  # 정수 인덱스인 경우

RangeIndex(start=0, stop=1675, step=1)

In [ ]:
df2 = df.set_index('종목명')

df2.index  # 레이블 인덱스인 경우                우

Index(['현대캐피탈1474', '국민은행3306이표일(3)07후-24', '현대커머셜236', '현대커머셜360-4',
       '팬택관련 채권', '효성화학259-2', '한화솔루션246-2', '한화솔루션246-2', '현대상선176-2',
       '현대상선176-2',
       ...
       '현대상선176-2', '현대상선176-2', '한진해운71-2', '한진해운71-2', '현대상선176-2',
       '현대상선176-2', '남제천농협 정기예치 (남제천농협)', '현대상선177-2', '동부메탈10-1', '한진해운76-2'],
      dtype='object', name='종목명', length=1675)

* 컬럼명(columns)

In [ ]:
df.columns

Index(['지역본부', '시군지부', '사무소명', '사무소코드', '과목', '상품종류', '종목명', '자산구분', '발행일',
       '만기일', '발행금리', '할인금리', '이자계산구분', '이자계산기간', '자산유동화구분', '매출일', '매입일',
       '신용등급', '매입수익률', '액면(좌수)', '장부금액', '미수이자', '예수법인세의제', '최초장부금액', '시장수익율',
       '발행회사', '거래회사', '농축협예수사무소코드', '평가손익', '매입신용등급', '계속보유여부검토대상'],
      dtype='object')

* 전치행렬(T)

In [ ]:
df.T

                  0                     1     ...         1673         1674
지역본부            강원지역본부                강원지역본부  ...       충북지역본부       충북지역본부
시군지부             강릉시지부                 강릉시지부  ...        충주시지부        충주시지부
사무소명              강릉농협                  강릉농협  ...         충주농협         충주농협
사무소코드           333050                333050  ...       417015       417015
과목                  채권                    채권  ...           채권           채권
상품종류               금융채                   금융채  ...          회사채          회사채
종목명          현대캐피탈1474  국민은행3306이표일(3)07후-24  ...     동부메탈10-1     한진해운76-2
자산구분              매도가능                  매도가능  ...         매도가능         매도가능
발행일         2014-01-07            2013-06-24  ...   2012-04-16   2012-06-07
만기일         2021-01-07            2020-06-24  ...   2020-02-16   2017-06-07
발행금리             3.969                  3.61  ...            2          5.9
할인금리                 0                     0  ...            0            0
이자계산구분             복리채           이표채(FRN,전환)  ...  이표채(FRN,전환)  이표채(FRN,전환)
이자계산기간            12개월                   3개월  ...          3개월          3개월
자산유동화구분            NaN                   NaN  ...          NaN          NaN
매출일         2014-01-07            2013-06-24  ...   2012-04-16   2012-06-07
매입일         2014-01-16            2014-04-07  ...   2012-04-17   2012-06-07
신용등급                AA                   AA+  ...          NaN          NaN
매입수익률             3.95                  3.56  ...         5.35          5.8
액면(좌수)      2000000000            2000000000  ...    240000000   1000000000
장부금액        2057414292            2019191187  ...    144888240            0
미수이자           1920391                     0  ...            0            0
예수법인세의제              0                     0  ...            0            0
최초장부금액      2002279609            2005653261  ...    240660067   1004300000
시장수익율            1.506                  1.21  ...        2.495        2.495
발행회사          현대캐피탈(주)               (주)국민은행  ...      (주)동부메탈      (주)한진해운
거래회사           삼성증권(주)               삼성증권(주)  ...  엔에이치투자증권(주)  엔에이치투자증권(주)
농축협예수사무소코드         NaN                   NaN  ...          NaN          NaN
평가손익          57020083              18721556  ...            0            0
매입신용등급             AA+                   AA+  ...         BBB+           A-
계속보유여부검토대상         NaN                   NaN  ...          NaN          NaN

[31 rows x 1675 columns]

* 행과 열의 축 수(shape)

In [ ]:
df.shape

(1675, 31)

#### 2) 요약 정보

* 앞에서 N번째 행만 골라보기(head)

In [ ]:
df.head(3)   # 기본값은 5

     지역본부   시군지부  사무소명   사무소코드  ... 농축협예수사무소코드      평가손익 매입신용등급 계속보유여부검토대상
0  강원지역본부  강릉시지부  강릉농협  333050  ...        NaN  57020083    AA+        NaN
1  강원지역본부  강릉시지부  강릉농협  333050  ...        NaN  18721556    AA+        NaN
2  강원지역본부  강릉시지부  강릉농협  333050  ...        NaN  70641649    AA-        NaN

[3 rows x 31 columns]

* 뒤에서 N번째 행만 골라보기(tail)

In [ ]:
df.tail(2)

        지역본부   시군지부  사무소명   사무소코드  ... 농축협예수사무소코드 평가손익 매입신용등급 계속보유여부검토대상
1673  충북지역본부  충주시지부  충주농협  417015  ...        NaN    0   BBB+        NaN
1674  충북지역본부  충주시지부  충주농협  417015  ...        NaN    0     A-        NaN

[2 rows x 31 columns]

* 컬럼별 결측치 없는 행의 수 계산(count)

In [ ]:
df.count()

지역본부          1675
시군지부          1675
사무소명          1675
사무소코드         1675
과목            1675
상품종류          1675
종목명           1675
자산구분          1675
발행일           1675
만기일           1675
발행금리          1675
할인금리          1675
이자계산구분        1675
이자계산기간        1675
자산유동화구분         45
매출일           1675
매입일           1675
신용등급           597
매입수익률         1675
액면(좌수)        1675
장부금액          1675
미수이자          1675
예수법인세의제       1675
최초장부금액        1675
시장수익율         1675
발행회사          1675
거래회사          1675
농축협예수사무소코드     194
평가손익          1675
매입신용등급        1215
계속보유여부검토대상      18
dtype: int64

* 컬럼별 자료형 확인(dtypes)

In [ ]:
df.dtypes

지역본부           object
시군지부           object
사무소명           object
사무소코드           int64
과목             object
상품종류           object
종목명            object
자산구분           object
발행일            object
만기일            object
발행금리          float64
할인금리            int64
이자계산구분         object
이자계산기간         object
자산유동화구분        object
매출일            object
매입일            object
신용등급           object
매입수익률         float64
액면(좌수)          int64
장부금액            int64
미수이자            int64
예수법인세의제         int64
최초장부금액          int64
시장수익율         float64
발행회사           object
거래회사           object
농축협예수사무소코드    float64
평가손익            int64
매입신용등급         object
계속보유여부검토대상     object
dtype: object

* 컬럼별 번호, count, dtypes 종합 확인(info)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1675 entries, 0 to 1674
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   지역본부        1675 non-null   object
 1   시군지부        1675 non-null   object
 2   사무소명        1675 non-null   object
 3   사무소코드       1675 non-null   int64
 4   과목          1675 non-null   object
 5   상품종류        1675 non-null   object
 6   종목명         1675 non-null   object
 7   자산구분        1675 non-null   object
 8   발행일         1675 non-null   object
 9   만기일         1675 non-null   object
 10  발행금리        1675 non-null   float64
 11  할인금리        1675 non-null   int64
 12  이자계산구분      1675 non-null   object
 13  이자계산기간      1675 non-null   object
 14  자산유동화구분     45 non-null     object
 15  매출일         1675 non-null   object
 16  매입일         1675 non-null   object
 17  신용등급        597 non-null    object
 18  매입수익률       1675 non-null   float64
 19  액면(좌수)      1675 non-null   int64
 20  장부금액        1675 non-null   int64
 21  미수이자        1675 non-null   int64
 22  예수법인세의제     1675 non-null   int64
 23  최초장부금액      1675 non-null   int64
 24  시장수익율       1675 non-null   float64
 25  발행회사        1675 non-null   object
 26  거래회사        1675 non-null   object
 27  농축협예수사무소코드  194 non-null    float64
 28  평가손익        1675 non-null   int64
 29  매입신용등급      1215 non-null   object
 30  계속보유여부검토대상  18 non-null     object
dtypes: float64(4), int64(8), object(19)
memory usage: 405.8+ KB

* 숫자형 컬럼들의 요약 통계량(describe)

In [ ]:
df.describe()

               사무소코드         발행금리  ...     농축협예수사무소코드          평가손익
count    1675.000000  1675.000000  ...     194.000000  1.675000e+03
mean   500254.777910     3.366505  ...  385383.551546  1.303219e+07
std    224111.835228     1.531165  ...  234473.520021  4.525814e+07
min    100012.000000     1.000000  ...  100056.000000 -7.051570e+08
25%    333050.000000     2.300000  ...  176909.000000  0.000000e+00
50%    483012.000000     3.312000  ...  234084.500000  0.000000e+00
75%    717100.000000     4.408000  ...  601111.000000  1.558899e+07
max    903024.000000    10.000000  ...  901125.000000  6.920212e+08

[8 rows x 12 columns]

### 2. 시리즈 탐색하기

* 고유한 자료값 목록 확인(unique)

In [ ]:
df.상품종류.unique()

array(['금융채', '금융채(특금)', '회사채', '채권형수익증권', '농축협예치금', '혼합형수익증권', '공사채',
       '기업어음', '기업어음(특금)', '자산유동화기업어음(ABCP)', '자산유동화기업어음(ABCP)(특금)', '국채',
       '회사채(특금)', '국채(첨가)', '제1금융기관(단기특정금전신탁)', '지방채', '채권형수익증권(특금)'],
      dtype=object)

* 자료값 목록별 개수 확인(value_counts)

In [ ]:
df.과목.value_counts()

채권        1251
대내외예치금     195
수익증권       179
유동자산        50
Name: 과목, dtype: int64